### ISSUE TITLE
Upgrade purescript-test-unit

### ISSUE THREAD

**Issue by tfausak** [tfausak/purescript-neon#108]
https://github.com/bodil/purescript-test-unit/tree/v6.0.0

Lots of breaking changes.

**Comment by tfausak** [comment]
purescript-test-unit is up to 9.0.0 now. It might be worthwhile to rewrite the test suite using something more stable, like purescript-assert and purescript-quickcheck.

**Comment by adius** [comment]
Fixed with 7a8f7ffd414c1aa19864df341a53f9c781580b2e
