### ISSUE TITLE
Can now upload to pursuit

### ISSUE THREAD

**Issue by hdgarrood** [tfausak/purescript-neon#87]
Just fyi: pursuit can now accept gzipped uploads, which means it's now possible to upload neon and batteries again. I've just uploaded neon-0.4.0 and batteries-0.5.1 for you.

You'll need to gzip the pursuit.json files from now on (because of their size). To do gzipped uploads, just gzip the request body, and add a `Content-Encoding: gzip` header.

**Comment by tfausak** [comment]
:+1: Good to know! I usually let Travis CI upload the docs. Since the build isn't finishing, I've just let it languish. Thanks for uploading new docs!

**Comment by hdgarrood** [comment]
No problem. :)

**Comment by tfausak** [comment]
For what it's worth, I was able to upload an uncompressed JSON file for Neon 0.4.1. It was less than 1 MB. I tried to upload a gzipped version but the upload page on Pursuit wouldn't let me. The form only accepts uncompressed application/json.

**Comment by hdgarrood** [comment]
Yeah, I didn't implement that yet, as I'm focusing on `pulp release` at the moment. I'm hoping that it won't be necessary at all after `pulp release`, actually.

**Comment by tfausak** [comment]
:+1: I look forward to `pulp release`!
